/**
 * POST /api/portraits/generate
 *
 * DUAL-FLOW: Works for both guests and authenticated subscribers.
 *
 * Runs the full portrait generation pipeline:
 *   analyze → build prompt → generate → watermark → store
 *
 * The portraitId must have been created via /api/portraits/upload-complete first.
 * The caller identifies themselves via sessionId (cookie) or Clerk auth.
 *
 * Authorization: a portrait can only be generated by its owner
 *   - Guest:      sessionId must match portrait.sessionId
 *   - Subscriber: userId must match portrait.userId (or portrait.userId is null and sessionId matches)
 */

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { prisma } from "@/lib/prisma";
import { generatePortrait } from "@/lib/services/portrait-generation";

// The synchronous pipeline (analysis → stand-in + fidelity gate → swap →
// acceptance gate, each leg with retries) routinely exceeds the project's
// 300s default — a live run died at FUNCTION_INVOCATION_TIMEOUT mid-stand-in
// (2026-07-12). 800s is the Fluid compute maximum on this plan.
export const maxDuration = 800;

export async function POST(request: NextRequest) {
  try {
    // --- Auth: optional ---
    let userId: string | null = null;
    try {
      const { userId: clerkUserId } = await auth();
      userId = clerkUserId;
    } catch {
      // Guest flow
    }

    // --- Parse request body ---
    let body: {
      portraitId?: string;
      stylePackSlug?: string;
      styleVariantSlug?: string;
      sessionId?: string;
      userScene?: string;
    };

    try {
      body = await request.json();
    } catch {
      return NextResponse.json(
        { success: false, error: "Invalid JSON body" },
        { status: 400 }
      );
    }

    const { portraitId, stylePackSlug, styleVariantSlug, sessionId, userScene } = body;

    if (!portraitId || !stylePackSlug || !styleVariantSlug) {
      return NextResponse.json(
        {
          success: false,
          error: "Required fields: portraitId, stylePackSlug, styleVariantSlug",
        },
        { status: 400 }
      );
    }

    // Custom scene requires userScene
    if (stylePackSlug === "custom-scene" && !userScene) {
      return NextResponse.json(
        { success: false, error: "Custom scene requires a userScene description" },
        { status: 400 }
      );
    }

    // --- Load portrait and verify ownership ---
    const portrait = await prisma.portrait.findUnique({
      where: { id: portraitId },
    });

    if (!portrait) {
      return NextResponse.json(
        { success: false, error: "Portrait not found" },
        { status: 404 }
      );
    }

    // Authorization check:
    // - Subscriber: must match userId
    // - Guest: must match sessionId
    const isOwner =
      (userId && portrait.userId === userId) ||
      (!userId && sessionId && portrait.sessionId === sessionId) ||
      (userId && !portrait.userId && sessionId && portrait.sessionId === sessionId);

    if (!isOwner) {
      return NextResponse.json(
        { success: false, error: "Not authorized to generate this portrait" },
        { status: 403 }
      );
    }

    // --- Check portrait is in a generatable state ---
    if (portrait.status === "generating" || portrait.status === "analyzing") {
      return NextResponse.json(
        { success: false, error: "Portrait is already being processed" },
        { status: 409 }
      );
    }

    if (portrait.status === "purchased") {
      return NextResponse.json(
        { success: false, error: "This portrait has already been purchased" },
        { status: 409 }
      );
    }

    // --- Run generation pipeline ---
    const result = await generatePortrait({
      portraitId,
      stylePackSlug,
      styleVariantSlug,
      userId,
      userScene,
    });

    if (!result.success) {
      const status =
        result.errorType === "quality"
          ? 422
          : result.errorType === "notfound"
          ? 404
          : 500;

      return NextResponse.json(
        {
          success: false,
          error: result.error,
          ...(result.qualityIssues && { qualityIssues: result.qualityIssues }),
        },
        { status }
      );
    }

    return NextResponse.json({
      success: true,
      portraitId,
      previewImageUrl: result.previewImageUrl,
      subjectType: result.subjectType,
    });
  } catch (error) {
    console.error("[Generate] Unexpected error:", error);
    return NextResponse.json(
      { success: false, error: "Generation failed. Please try again." },
      { status: 500 }
    );
  }
}
